UPDATE league_tiers
SET benefits_json = '{"ro":[{"icon":"✓","category":"access","description":"Acces la dashboard investitor","order":1},{"icon":"📊","category":"analytics","description":"Statistici lunare bază","order":2},{"icon":"💬","category":"support","description":"Suport email standard","order":3}],"en":[{"icon":"✓","category":"access","description":"Investor dashboard access","order":1},{"icon":"📊","category":"analytics","description":"Basic monthly statistics","order":2},{"icon":"💬","category":"support","description":"Standard email support","order":3}]}'
WHERE tier_code = 'ENTRY';
UPDATE league_tiers
SET benefits_json = '{"ro":[{"icon":"⚡","category":"fees","description":"Discount 5% la comisioane retragere","order":1},{"icon":"📊","category":"analytics","description":"Rapoarte săptămânale detaliate","order":2},{"icon":"💬","category":"support","description":"Suport prioritar chat live","order":3},{"icon":"🎯","category":"priority","description":"Acces prioritar la oportunități noi","order":4}],"en":[{"icon":"⚡","category":"fees","description":"5% discount on withdrawal fees","order":1},{"icon":"📊","category":"analytics","description":"Detailed weekly reports","order":2},{"icon":"💬","category":"support","description":"Priority live chat support","order":3},{"icon":"🎯","category":"priority","description":"Priority access to new opportunities","order":4}]}'
WHERE tier_code = 'SILVER';
UPDATE league_tiers
SET benefits_json = '{"ro":[{"icon":"💰","category":"fees","description":"Discount 10% la toate comisioanele","order":1},{"icon":"📈","category":"analytics","description":"Dashboard personalizat cu predicții AI","order":2},{"icon":"👨‍💼","category":"support","description":"Account manager dedicat","order":3},{"icon":"🚀","category":"priority","description":"Early access la produse noi","order":4},{"icon":"🎁","category":"rewards","description":"Bonus lunar pe bază de performance","order":5}],"en":[{"icon":"💰","category":"fees","description":"10% discount on all fees","order":1},{"icon":"📈","category":"analytics","description":"Personalized dashboard with AI predictions","order":2},{"icon":"👨‍💼","category":"support","description":"Dedicated account manager","order":3},{"icon":"🚀","category":"priority","description":"Early access to new products","order":4},{"icon":"🎁","category":"rewards","description":"Monthly performance bonus","order":5}]}'
WHERE tier_code = 'GOLD';
UPDATE league_tiers
SET benefits_json = '{"ro":[{"icon":"💎","category":"fees","description":"Discount 20% + cashback lunar 2%","order":1},{"icon":"🤖","category":"analytics","description":"AI trading signals în timp real","order":2},{"icon":"📞","category":"support","description":"Hotline 24/7 + WhatsApp direct","order":3},{"icon":"🏆","category":"priority","description":"Acces VIP la evenimente exclusive","order":4},{"icon":"💼","category":"consulting","description":"Consultanță strategică trimestrială","order":5},{"icon":"🎖️","category":"rewards","description":"Programe de loialitate premium","order":6}],"en":[{"icon":"💎","category":"fees","description":"20% discount + 2% monthly cashback","order":1},{"icon":"🤖","category":"analytics","description":"Real-time AI trading signals","order":2},{"icon":"📞","category":"support","description":"24/7 hotline + direct WhatsApp","order":3},{"icon":"🏆","category":"priority","description":"VIP access to exclusive events","order":4},{"icon":"💼","category":"consulting","description":"Quarterly strategic consulting","order":5},{"icon":"🎖️","category":"rewards","description":"Premium loyalty programs","order":6}]}'
WHERE tier_code = 'PRO';